---
- name: Install git
  become: yes
  apt:
    name: git
    state: present
    update_cache: true

- name: Download repository
  git:
    repo: "{{ repo }}"
    dest: asv-suite

- name: Copy machine info
  template:
    src: asv-machine.json.j2
    dest: /home/{{ ansible_user }}/.asv-machine.json

- name: Run benchmarks
  command: /home/{{ ansible_user }}/miniconda3/envs/asv/bin/asv run --machine="{{ machine.name }}"
  args:
    chdir: /home/{{ ansible_user }}/asv-suite/{{ item }}
  with_items:
    "{{ repos }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/miniconda3/bin"
  tags:
    - benchmarks

# - name: Publish benchmarks
#   s3:
#     bucket: "{{ s3_bucket }}"
#     object: "{{ }}"
#     src: "{{ }}"
#     mode: put
