---
- name: Install system packages
  become: yes
  apt:
    name:
      - git
      - python-pip
    state: present
    update_cache: true
  tags:
    - packages

- name: Install system python packages
  become: yes
  pip:
    name:
      - boto
      - python-dateutil
      - boto3
  tags:
    - aws
    - s3

- name: Ensure S3 bucket exists
  become: no
  s3_bucket:
    name: "{{ s3_bucket }}"
    tags: "{{ s3_tags }}"
  tags:
    - aws
    - s3
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

- name: Download repository
  git:
    repo: "{{ repo }}"
    dest: "{{ workdir }}"

- name: Copy machine info
  template:
    src: asv-machine.json.j2
    dest: /home/{{ ansible_user }}/.asv-machine.json

- name: Run benchmarks
  command: "{{ miniconda_dir }}/envs/asv/bin/asv run --machine={{ machine.name }}"
  args:
    chdir: "{{ workdir }}/{{ item }}"
  with_items:
    "{{ benchmark_repos }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ miniconda_dir }}/bin"
  tags:
    - benchmarks

- name: Publish benchmarks
  s3_sync:
    bucket: "{{ s3_bucket }}"
    file_root: "{{ workdir }}/{{ item }}/.asv/results"
    key_prefix: "{{ item }}"
  with_items: 
    "{{ benchmark_repos }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags:
    - s3
    - publish
