---
- name: Install system packages
  become: yes
  apt:
    name:
      - git
      - python-pip
    state: present
    update_cache: true
  tags:
    - packages

- name: Install system python packages
  become: yes
  pip:
    name:
      - boto
      - python-dateutil
      - boto3
  tags:
    - aws
    - s3

- name: Copy machine info
  template:
    src: asv-machine.json.j2
    dest: /home/{{ ansible_user }}/.asv-machine.json

- name: Copy master runner
  template:
    src: benchmark_runner.sh
    dest: /usr/local/bin/benchmark_runner
    mode: 0755
  become: yes
  tags:
    - runners

- name: Ensure runners directory
  file:
    path: /home/{{ ansible_user }}/runners
    state: directory
  tags:
    - runners

- name: Copy runner script
  template:
    src: run.sh.j2
    dest: /home/{{ ansible_user }}/runners/{{ item.project }}.sh
    mode: 0755
  with_items: "{{ repositories }}"
  tags:
    - runners

- name: Add cron job
  cron:
    name: "Run benchmarks"
    minute: "0"
    hour: "0"
    job: "/usr/local/bin/benchmark_runner"
  tags:
    - runners

- name: Download repositories
  git:
    repo: "{{ item.url }}"
    dest: "/home/{{ ansible_user }}/{{ item.project }}"
  with_items: "{{ repositories }}"
